### ISSUE TITLE
[iOS] En tant qu'utilisateur, je peux consulter la liste des demandes de prêts

### ISSUE THREAD

**Issue by VictorLuc4** [HETIC-W3-G12/iOS-Application#2]
## Description générale

En tant qu'utilisateur, je peux consulter la liste des demandes de prêts. 
Sur l'application se verra affichée la liste de toutes les demandes de prêt en cours.

## Pré-requis

* @Abelia 
    - [x] Besoin Maquettes
* @MRWS @samchery 
lien : https://github.com/HETIC-W3-G12/node-api/issues/7
    - [x] API : Liste des projets
* Basée sur la branche : Connexion-Inscription

## Todo Liste

- [x] ViewController
- [x] Custom Cells
- [x] API Request
- [x] Request Handling
- [x] Transfer Data to the ProjectVC on cell clic

**Comment by MRWS** [comment]
- [ ] Bonjour
